version: "3.9"

x-bot-base: &bot-base
  build: .
  env_file:
    - .env
  volumes:
    - ./logs:/app/logs
  restart: unless-stopped

services:
  monitoring:
    <<: *bot-base
    command: ["python", "-m", "monitoring.server", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8000:8000"

  binance_bot:
    <<: *bot-base
    command: ["python", "deepseek.py"]
    depends_on:
      - monitoring

  okx_bot:
    <<: *bot-base
    command: ["python", "deepseek_ok版本.py"]
    depends_on:
      - monitoring

  okx_plus_bot:
    <<: *bot-base
    command: ["python", "deepseek_ok_带指标plus版本.py"]
    depends_on:
      - monitoring
